---
version: '2'
services:
  agent:
    image: inspectit/inspectit-ocelot-agent:ocelot-meets-friends
    container_name: agent
    mem_limit: 128M
    volumes:
      - agent-vol:/agent

  ocelot-config-server:
    image: inspectit/inspectit-ocelot-configurationserver:ocelot-meets-friends
    container_name: ocelot-config-server
    mem_limit: 256M
    environment:
      - INSPECTIT_CONFIG_SERVER_WORKING_DIRECTORY=/configuration-server
      - INSPECTIT_CONFIG_SERVER_DEFAULT_USER_PASSWORD=demo
    volumes:
      - ./configuration-server:/configuration-server
    ports:
      - 8090:8090

  config-server:
    image: inspectit/spring-petclinic-config-server:ocelot-meets-friends
    container_name: config-server
    depends_on:
      - ocelot-config-server
      - agent
    environment:
      - INSPECTIT_SERVICE_NAME=config-server
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT=9096
      - INSPECTIT_PLUGINS_PATH=/ocelot-plugins
      - INSPECTIT_PLUGINS_DATADOG_URL=http://dd-agent:8126/v0.3/traces
    mem_limit: 512M
    entrypoint: ["sh", "-c","
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
      - ./ocelot-plugins:/ocelot-plugins
    ports:
      - 8888:8888
      - 9096:9096

  discovery-server:
    image: inspectit/spring-petclinic-discovery-server:ocelot-meets-friends
    container_name: discovery-server
    environment:
      - INSPECTIT_SERVICE_NAME=discovery-server
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT=9095
      - INSPECTIT_PLUGINS_PATH=/ocelot-plugins
      - INSPECTIT_PLUGINS_DATADOG_URL=http://dd-agent:8126/v0.3/traces
    mem_limit: 512M
    depends_on:
      - ocelot-config-server
      - agent
      - config-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
      - ./ocelot-plugins:/ocelot-plugins
    ports:
      - 8761:8761
      - 9095:9095

  customers-service:
    image: inspectit/spring-petclinic-customers-service:ocelot-meets-friends
    container_name: customers-service
    environment:
      - INSPECTIT_SERVICE_NAME=customers-service
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT=9091
      - INSPECTIT_PLUGINS_PATH=/ocelot-plugins
      - INSPECTIT_PLUGINS_DATADOG_URL=http://dd-agent:8126/v0.3/traces
    mem_limit: 512M
    depends_on:
      - ocelot-config-server
      - agent
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
      - ./ocelot-plugins:/ocelot-plugins
    ports:
      - 8081:8081
      - 9091:9091

  visits-service:
    image: inspectit/spring-petclinic-visits-service:ocelot-meets-friends
    container_name: visits-service
    environment:
      - INSPECTIT_SERVICE_NAME=visits-service
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT=9092
      - INSPECTIT_PLUGINS_PATH=/ocelot-plugins
      - INSPECTIT_PLUGINS_DATADOG_URL=http://dd-agent:8126/v0.3/traces
    mem_limit: 512M
    depends_on:
      - ocelot-config-server
      - agent
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
      - ./ocelot-plugins:/ocelot-plugins
    ports:
      - 8082:8082
      - 9092:9092

  vets-service:
    image: inspectit/spring-petclinic-vets-service:ocelot-meets-friends
    container_name: vets-service
    environment:
      - INSPECTIT_SERVICE_NAME=vets-service
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT=9093
      - INSPECTIT_PLUGINS_PATH=/ocelot-plugins
      - INSPECTIT_PLUGINS_DATADOG_URL=http://dd-agent:8126/v0.3/traces
    mem_limit: 512M
    depends_on:
      - ocelot-config-server
      - agent
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
      - ./ocelot-plugins:/ocelot-plugins
    ports:
      - 8083:8083
      - 9093:9093

  api-gateway:
    image: inspectit/spring-petclinic-api-gateway:ocelot-meets-friends
    container_name: api-gateway
    environment:
      - INSPECTIT_SERVICE_NAME=api-gateway
      - INSPECTIT_CONFIG_HTTP_URL=http://ocelot-config-server:8090/api/v1/agent/configuration
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT=9094
      - INSPECTIT_PLUGINS_PATH=/ocelot-plugins
      - INSPECTIT_PLUGINS_DATADOG_URL=http://dd-agent:8126/v0.3/traces
    mem_limit: 512M
    depends_on:
      - ocelot-config-server
      - agent
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-ocelot-agent.jar
      -jar /app.jar"]
    volumes:
      - agent-vol:/agent
      - ./ocelot-plugins:/ocelot-plugins
    ports:
      - 8080:8080
      - 9094:9094

  load:
    image: inspectit/spring-petclinic-load:ocelot-meets-friends
    container_name: load-generator

  dd-agent:
    image: datadog/agent:7.18.0-rc.4
    container_name: dd-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.eu
      - DD_BIND_HOST=0.0.0.0
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
#     - DD_APM_ANALYZED_SPANS=api-gateway|;servlet.request=1
      - DD_LOG_LEVEL=debug
    ports:
      - 8126:8126
    volumes:
      - ./datadog:/conf.d

volumes:
  agent-vol:
