# This configuration defines the application based on the url called at the API-gateway.
# The application is propagated with service calls.
inspectit:
  instrumentation:  
    actions:
      get_servlet_application:
        imports:
          - javax.servlet
          - javax.servlet.http
        input:
          _arg0: ServletRequest
        value-body: |
          if(_arg0 instanceof HttpServletRequest) {
            String path = ((HttpServletRequest)_arg0).getServletPath();
            if (path.contains("vets")) {
              return "veterinarians";
            } else if(path.contains("owner")){
              return "customers";          
            }
          }
          return null;
           
    rules:    
      servlet_detect_application:
        scopes:
          servletapi_servlet_service: true
          servletapi_filter_doFilter: true
        entry:
          application: 
            action: get_servlet_application
            only-if-null: application